name: blueprint_app
description: A mobile app for generating 2D floor plans and connecting users with nearby vendors.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: any
  provider: any
  cached_network_image: any
  google_fonts: any
  permission_handler: any
  firebase_core: any
  firebase_auth: any
  cloud_firestore: any
  firebase_messaging: any
  geolocator: any
  url_launcher: ^6.1.11
  firebase_storage: ^12.4.4
  image_picker: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/  # Add your assets folder if needed
